[workspace]
members = [
    "opaque_typedef",
    "opaque_typedef_macros",
    "opaque_typedef_tests",
]

[patch.crates-io]
opaque_typedef = { path = "opaque_typedef" }
opaque_typedef_macros = { path = "opaque_typedef_macros" }
