[package]
name = "opaque_typedef_tests"
version = "0.0.5"
authors = ["YOSHIOKA Takuma <tashioka.256@gmail.com>"]
license = "MIT OR Apache-2.0"
readme = "README.md"

[dependencies]
opaque_typedef = "0.0.5"
opaque_typedef_macros = "0.0.5"
